// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/mirror"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MirrorCreate is the builder for creating a Mirror entity.
type MirrorCreate struct {
	config
	mutation *MirrorMutation
	hooks    []Hook
}

// SetOriginPath sets the "originPath" field.
func (mc *MirrorCreate) SetOriginPath(s string) *MirrorCreate {
	mc.mutation.SetOriginPath(s)
	return mc
}

// SetTargetPath sets the "targetPath" field.
func (mc *MirrorCreate) SetTargetPath(s string) *MirrorCreate {
	mc.mutation.SetTargetPath(s)
	return mc
}

// Mutation returns the MirrorMutation object of the builder.
func (mc *MirrorCreate) Mutation() *MirrorMutation {
	return mc.mutation
}

// Save creates the Mirror in the database.
func (mc *MirrorCreate) Save(ctx context.Context) (*Mirror, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MirrorCreate) SaveX(ctx context.Context) *Mirror {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MirrorCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MirrorCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MirrorCreate) check() error {
	if _, ok := mc.mutation.OriginPath(); !ok {
		return &ValidationError{Name: "originPath", err: errors.New(`ent: missing required field "Mirror.originPath"`)}
	}
	if v, ok := mc.mutation.OriginPath(); ok {
		if err := mirror.OriginPathValidator(v); err != nil {
			return &ValidationError{Name: "originPath", err: fmt.Errorf(`ent: validator failed for field "Mirror.originPath": %w`, err)}
		}
	}
	if _, ok := mc.mutation.TargetPath(); !ok {
		return &ValidationError{Name: "targetPath", err: errors.New(`ent: missing required field "Mirror.targetPath"`)}
	}
	return nil
}

func (mc *MirrorCreate) sqlSave(ctx context.Context) (*Mirror, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MirrorCreate) createSpec() (*Mirror, *sqlgraph.CreateSpec) {
	var (
		_node = &Mirror{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(mirror.Table, sqlgraph.NewFieldSpec(mirror.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.OriginPath(); ok {
		_spec.SetField(mirror.FieldOriginPath, field.TypeString, value)
		_node.OriginPath = value
	}
	if value, ok := mc.mutation.TargetPath(); ok {
		_spec.SetField(mirror.FieldTargetPath, field.TypeString, value)
		_node.TargetPath = value
	}
	return _node, _spec
}

// MirrorCreateBulk is the builder for creating many Mirror entities in bulk.
type MirrorCreateBulk struct {
	config
	err      error
	builders []*MirrorCreate
}

// Save creates the Mirror entities in the database.
func (mcb *MirrorCreateBulk) Save(ctx context.Context) ([]*Mirror, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Mirror, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MirrorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MirrorCreateBulk) SaveX(ctx context.Context) []*Mirror {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MirrorCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MirrorCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
