// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/db/ent/mirror"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Mirror is the model entity for the Mirror schema.
type Mirror struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OriginPath holds the value of the "originPath" field.
	OriginPath string `json:"originPath,omitempty"`
	// TargetPath holds the value of the "targetPath" field.
	TargetPath   string `json:"targetPath,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mirror) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mirror.FieldID:
			values[i] = new(sql.NullInt64)
		case mirror.FieldOriginPath, mirror.FieldTargetPath:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mirror fields.
func (m *Mirror) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mirror.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int(value.Int64)
		case mirror.FieldOriginPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field originPath", values[i])
			} else if value.Valid {
				m.OriginPath = value.String
			}
		case mirror.FieldTargetPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field targetPath", values[i])
			} else if value.Valid {
				m.TargetPath = value.String
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Mirror.
// This includes values selected through modifiers, order, etc.
func (m *Mirror) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// Update returns a builder for updating this Mirror.
// Note that you need to call Mirror.Unwrap() before calling this method if this Mirror
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Mirror) Update() *MirrorUpdateOne {
	return NewMirrorClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Mirror entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Mirror) Unwrap() *Mirror {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Mirror is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Mirror) String() string {
	var builder strings.Builder
	builder.WriteString("Mirror(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("originPath=")
	builder.WriteString(m.OriginPath)
	builder.WriteString(", ")
	builder.WriteString("targetPath=")
	builder.WriteString(m.TargetPath)
	builder.WriteByte(')')
	return builder.String()
}

// Mirrors is a parsable slice of Mirror.
type Mirrors []*Mirror
