// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/db/ent/mirror"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MirrorCreate is the builder for creating a Mirror entity.
type MirrorCreate struct {
	config
	mutation *MirrorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOriginPath sets the "originPath" field.
func (mc *MirrorCreate) SetOriginPath(s string) *MirrorCreate {
	mc.mutation.SetOriginPath(s)
	return mc
}

// SetTargetPath sets the "targetPath" field.
func (mc *MirrorCreate) SetTargetPath(s string) *MirrorCreate {
	mc.mutation.SetTargetPath(s)
	return mc
}

// Mutation returns the MirrorMutation object of the builder.
func (mc *MirrorCreate) Mutation() *MirrorMutation {
	return mc.mutation
}

// Save creates the Mirror in the database.
func (mc *MirrorCreate) Save(ctx context.Context) (*Mirror, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MirrorCreate) SaveX(ctx context.Context) *Mirror {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MirrorCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MirrorCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MirrorCreate) check() error {
	if _, ok := mc.mutation.OriginPath(); !ok {
		return &ValidationError{Name: "originPath", err: errors.New(`ent: missing required field "Mirror.originPath"`)}
	}
	if v, ok := mc.mutation.OriginPath(); ok {
		if err := mirror.OriginPathValidator(v); err != nil {
			return &ValidationError{Name: "originPath", err: fmt.Errorf(`ent: validator failed for field "Mirror.originPath": %w`, err)}
		}
	}
	if _, ok := mc.mutation.TargetPath(); !ok {
		return &ValidationError{Name: "targetPath", err: errors.New(`ent: missing required field "Mirror.targetPath"`)}
	}
	return nil
}

func (mc *MirrorCreate) sqlSave(ctx context.Context) (*Mirror, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MirrorCreate) createSpec() (*Mirror, *sqlgraph.CreateSpec) {
	var (
		_node = &Mirror{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(mirror.Table, sqlgraph.NewFieldSpec(mirror.FieldID, field.TypeInt))
	)
	_spec.OnConflict = mc.conflict
	if value, ok := mc.mutation.OriginPath(); ok {
		_spec.SetField(mirror.FieldOriginPath, field.TypeString, value)
		_node.OriginPath = value
	}
	if value, ok := mc.mutation.TargetPath(); ok {
		_spec.SetField(mirror.FieldTargetPath, field.TypeString, value)
		_node.TargetPath = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Mirror.Create().
//		SetOriginPath(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MirrorUpsert) {
//			SetOriginPath(v+v).
//		}).
//		Exec(ctx)
func (mc *MirrorCreate) OnConflict(opts ...sql.ConflictOption) *MirrorUpsertOne {
	mc.conflict = opts
	return &MirrorUpsertOne{
		create: mc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Mirror.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mc *MirrorCreate) OnConflictColumns(columns ...string) *MirrorUpsertOne {
	mc.conflict = append(mc.conflict, sql.ConflictColumns(columns...))
	return &MirrorUpsertOne{
		create: mc,
	}
}

type (
	// MirrorUpsertOne is the builder for "upsert"-ing
	//  one Mirror node.
	MirrorUpsertOne struct {
		create *MirrorCreate
	}

	// MirrorUpsert is the "OnConflict" setter.
	MirrorUpsert struct {
		*sql.UpdateSet
	}
)

// SetTargetPath sets the "targetPath" field.
func (u *MirrorUpsert) SetTargetPath(v string) *MirrorUpsert {
	u.Set(mirror.FieldTargetPath, v)
	return u
}

// UpdateTargetPath sets the "targetPath" field to the value that was provided on create.
func (u *MirrorUpsert) UpdateTargetPath() *MirrorUpsert {
	u.SetExcluded(mirror.FieldTargetPath)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Mirror.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MirrorUpsertOne) UpdateNewValues() *MirrorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.OriginPath(); exists {
			s.SetIgnore(mirror.FieldOriginPath)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Mirror.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MirrorUpsertOne) Ignore() *MirrorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MirrorUpsertOne) DoNothing() *MirrorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MirrorCreate.OnConflict
// documentation for more info.
func (u *MirrorUpsertOne) Update(set func(*MirrorUpsert)) *MirrorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MirrorUpsert{UpdateSet: update})
	}))
	return u
}

// SetTargetPath sets the "targetPath" field.
func (u *MirrorUpsertOne) SetTargetPath(v string) *MirrorUpsertOne {
	return u.Update(func(s *MirrorUpsert) {
		s.SetTargetPath(v)
	})
}

// UpdateTargetPath sets the "targetPath" field to the value that was provided on create.
func (u *MirrorUpsertOne) UpdateTargetPath() *MirrorUpsertOne {
	return u.Update(func(s *MirrorUpsert) {
		s.UpdateTargetPath()
	})
}

// Exec executes the query.
func (u *MirrorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MirrorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MirrorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MirrorUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MirrorUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MirrorCreateBulk is the builder for creating many Mirror entities in bulk.
type MirrorCreateBulk struct {
	config
	err      error
	builders []*MirrorCreate
	conflict []sql.ConflictOption
}

// Save creates the Mirror entities in the database.
func (mcb *MirrorCreateBulk) Save(ctx context.Context) ([]*Mirror, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Mirror, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MirrorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MirrorCreateBulk) SaveX(ctx context.Context) []*Mirror {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MirrorCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MirrorCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Mirror.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MirrorUpsert) {
//			SetOriginPath(v+v).
//		}).
//		Exec(ctx)
func (mcb *MirrorCreateBulk) OnConflict(opts ...sql.ConflictOption) *MirrorUpsertBulk {
	mcb.conflict = opts
	return &MirrorUpsertBulk{
		create: mcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Mirror.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mcb *MirrorCreateBulk) OnConflictColumns(columns ...string) *MirrorUpsertBulk {
	mcb.conflict = append(mcb.conflict, sql.ConflictColumns(columns...))
	return &MirrorUpsertBulk{
		create: mcb,
	}
}

// MirrorUpsertBulk is the builder for "upsert"-ing
// a bulk of Mirror nodes.
type MirrorUpsertBulk struct {
	create *MirrorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Mirror.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MirrorUpsertBulk) UpdateNewValues() *MirrorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.OriginPath(); exists {
				s.SetIgnore(mirror.FieldOriginPath)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Mirror.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MirrorUpsertBulk) Ignore() *MirrorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MirrorUpsertBulk) DoNothing() *MirrorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MirrorCreateBulk.OnConflict
// documentation for more info.
func (u *MirrorUpsertBulk) Update(set func(*MirrorUpsert)) *MirrorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MirrorUpsert{UpdateSet: update})
	}))
	return u
}

// SetTargetPath sets the "targetPath" field.
func (u *MirrorUpsertBulk) SetTargetPath(v string) *MirrorUpsertBulk {
	return u.Update(func(s *MirrorUpsert) {
		s.SetTargetPath(v)
	})
}

// UpdateTargetPath sets the "targetPath" field to the value that was provided on create.
func (u *MirrorUpsertBulk) UpdateTargetPath() *MirrorUpsertBulk {
	return u.Update(func(s *MirrorUpsert) {
		s.UpdateTargetPath()
	})
}

// Exec executes the query.
func (u *MirrorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MirrorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MirrorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MirrorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
